### PR TITLE
Supply a serverName when creating a connectToServer action

### LINKED ISSUE #372: [Suggestion] Supply the server name when connecting to the server
The ServerData serverName seems to be set to null when clicking a button with action connectToServer. This causes some other mods to crash, as they expect a server name to be there, and use it to name folders (see https://github.com/Tropicraft/Tropicraft/blob/1.12.2/src/main/java/net/tropicraft/core/encyclopedia/TropicalBook.java#L92).

The fix for this would be one of:
- Allow the serverName to be specified in the configuration
- Supply a serverName that is the same as the server IP

### PR DESCRIPTION
**Pull request by mysticdrew**
Fixes #372

### CODE REVIEW

**Comment by TheNasbit** [comment]
@mysticdrew is this feature live yet?

**Comment by mysticdrew** [comment]
> @mysticdrew is this feature live yet?

You can build my fork if you want, otherwise you'll need to wait for @lumien231 to merge my PR and publish it.

**Comment by lumien231** [comment]
Sorry, didn't notice someone actually created a pr 😅.

**Comment by Brycey92** [comment]
Wow, wish I had known this was an open-source mod a while ago! I had gone and decompiled this and spent about 3 full days fixing the decompiler output, tracking down the bug from JourneyMap into this mod, and making my damn kludgy mess compile. :joy: :sob: Ended up being just a few lines of changes, same as here.

Anyway, thanks for fixing this on the official mod, you guys! :+1:

**Pull request merged**
